### ISSUE TITLE
Oauth app vs Github app

### ISSUE THREAD

**Issue by lawrend** [learn-co-curriculum/rails-github-api#14]
The linked tutorial references a Github app. However, to access scopes the app must be a new Oauth app. Following the tutorial could lead to students attempting this lab using a Github app, and that is headache-ville.

**Comment by DanielSeehausen** [comment]
Hi there,

Would you mind providing a bit more detail about the issue? Things that are especially useful:

An expanded explanation of what's going on.
Steps to reproduce the issue.
Details about your environment.
What's your operating system? Which version?
Are you using the Learn IDE or a local development environment?
A stack trace of any errors.
Thanks! 💙
