### ISSUE TITLE
Instructions need update / solution code is depracated

### ISSUE THREAD

**Issue by jmstrick93** [learn-co-curriculum/rails-github-api#15]
After trying with both the code from the solution branch and Dakota's code that previously worked, we were not able to successfully make a POST request to the Github API.  All requests keep coming back with a 404 Not Found response.  It is possible that the Github API has changed?  In any case, this lab needs some love.

**Comment by kyleblee** [comment]
I think the confusion comes from the instructions not calling out the need to pass in a `scope` parameter with a value of `public_repo` during [step 1 of the authorization process](https://developer.github.com/apps/building-oauth-apps/authorization-options-for-oauth-apps/#web-application-flow). After banging my head against my computer for about an hour, I tried adding the parameter upon reading that it [granted read/write access to a user's public repositories](https://developer.github.com/apps/building-oauth-apps/scopes-for-oauth-apps/#available-scopes).

Wasn't a fun hour and could be avoided with a little more instruction, if this is indeed the fix.

**Comment by DanielSeehausen** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
