### ISSUE TITLE
requires "your_username" to be displayed

### ISSUE THREAD

**Issue by jmb521** [learn-co-curriculum/rails-github-api#17]
In order to pass the tests, the browser needs to see "your_username"

line 6 of repos_spec.rb  -->    expect(page).to have_content 'your_username'

should accept session[:username] as the way to display the username in the browser and pass the test.

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
issue #27. 

We will add this to our internal work queue. We are in the process of updating
the materials in this section and will be rewriting this lesson to address the
current issues. We'll be taking all of this information into consideration in
upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress. We will notify
you when it is resolved.

Thanks for contributing!
