### ISSUE TITLE
Requesting headers & passing params in body

### ISSUE THREAD

**Issue by dtow55** [learn-co-curriculum/rails-github-api#18]
1) In this lab, it was necessary to request an 'Accept' header in the Faraday request. Instructions on how to do this have not been covered thus far in the curriculum, and answers on Google were not basic enough to understand easily. I think it would be VERY helpful to include a section explaining that the tests/Github require a header request to be sent, and show how to do it.

2) It was also necessary to send a body JSON object in the request to make the tests pass. What was really confusing was that Github does not require you to do it this way (Github will handle it if you send params in the URL), so when I was testing manually, it seemed like it was working. Yet the tests were failing and the failure errors were very difficult to read (I did not realize they were failing only because they wanted me to pass params through a body JSON). I think it would be VERY helpful here to include a note to students along the lines of, "Github will handle params passed in the URL; however, the tests may require you to include the params in the body. If you see a test error that reads "......", the issue is likely that you are passing params in the URL and not as a body JSON. Here is a link to the the previous lesson which explains how to do this: [link]"

CODE THAT REQUIRES BODY JSON and HEADER REQUEST:
    resp = Faraday.post url do |req|
      req.body = { 'client_id': client_id, 'client_secret': client_secret, 'code': code }
      req.headers['Accept'] = 'application/json'
    end

**Comment by hansenjl** [comment]
I would like to reiterate this point. All examples leading up to this lab show Faraday requests using params only. Using params works to make the request and works in the browser but does not meet the test requirements. The specs require that the request be sent as shown above, which is a format not shown in any previous examples.  This can be very frustrating for students especially because it works in the browser but does not pass tests. 

@DanielSeehausen

**Comment by sgharms** [comment]
This project issue is under review and will be addressed shortly.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @dtow55 and @hansenjl.

We have updated the materials and included information headers and body requests in Faraday and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
