### ISSUE TITLE
Cannot run learn or rails s. Nokogiri error

### ISSUE THREAD

**Issue by CatalanoWebDevelopment** [learn-co-curriculum/rails-github-api#19]
Error with building native extensions. Lab is not working. 

Gem files will remain installed in
/Users/parkercatalano/.rvm/gems/ruby-2.3.3/gems/nokogiri-1.6.6.2 for inspection.
Results logged to
/Users/parkercatalano/.rvm/gems/ruby-2.3.3/extensions/x86_64-darwin-17/2.3.0/nokogiri-1.6.6.2/gem_make.out

An error occurred while installing nokogiri (1.6.6.2), and Bundler
cannot continue.
Make sure that `gem install nokogiri -v '1.6.6.2'` succeeds before bundling.

In Gemfile:
  rails was resolved to 4.2.1, which depends on
    actionmailer was resolved to 4.2.1, which depends on
      actionpack was resolved to 4.2.1, which depends on
        actionview was resolved to 4.2.1, which depends on
          rails-dom-testing was resolved to 1.0.6, which depends on
            nokogiri

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials, including the Gemfile contents and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
