### ISSUE TITLE
gem 'rack_session_access' causes  issues running rails server

### ISSUE THREAD

**Issue by NStephenson** [learn-co-curriculum/rails-github-api#22]
This gem is placed in the test block of the config file, however it's used in the development configuration file, which causes running the rails server to fail. To resolve this issue, the gem needs to be removed from the test block.

**Comment by JoeQuattrone** [comment]
Hi, I did that and ran `bundle update`, but I'm still getting the `uninitialized constant RackSessionAccess (NameError)` error. Was there anything else you did to resolve this issue?

**Comment by micahshute** [comment]
@JoeQuattrone try commenting out line 47 in `config/environments/development.rb`

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
