### ISSUE TITLE
Bug with update causes uninitialized constant RackSessionAccess error

### ISSUE THREAD

**Issue by micahshute** [learn-co-curriculum/rails-github-api#23]
__Summary:__ uninitialized constant RackSessionAccess error raised when students try to run `rake` or `rails` commands

__Fix:__ Remove line 47 from `config/environments/development.rb`, it does not seem to be compatible with the newer version of rails after the update.

**Comment by morgvanny** [comment]
thank you!!

**Comment by FionaDL** [comment]
Yes, thank you!

**Comment by ChrstphGrnr** [comment]
Thank you!

**Comment by catherinism** [comment]
thank you!

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
