### ISSUE TITLE
authentication & visiting root: JSON::ParserError: A JSON text must at least contain two octets!

### ISSUE THREAD

**Issue by ICanDoAllThingThroughChrist** [learn-co-curriculum/rails-github-api#25]

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
issue #27. 

We will add this to our internal work queue. We are in the process of updating
the materials in this section and will be rewriting this lesson to address the
current issues. We'll be taking all of this information into consideration in
upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress. We will notify
you when it is resolved.

Thanks for contributing!
