### ISSUE TITLE
stub request spec change

### ISSUE THREAD

**Issue by pajamaw** [learn-co-curriculum/rails-github-api#6]
despite being able to create new repo's with my application, kept coming up with this error. the difference in the two i found was " with(:body => {"{\"name\":\"a-new-repo\"}"=>nil}" , which was tested in line 29 of spec_helper.rb
      with(:body => {"{\"name\":\"a-new-repo\"}"=>true},
it was only when i changed the spec to nil i was able to pass the test, and still be able to successfully generate a new repo in github. https://github.com/pajamaw/New-Repo-
sorry if i'm incorrect about there being an issue or not, but after comparing this lab with the refactoring lab i think there might be a problem. 

```
 WebMock::NetConnectNotAllowedError:
   Real HTTP connections are disabled. Unregistered request: POST https://api.github.com/user/repos with body '{"name":"a-new-repo"}' with headers {'Accept'=>'application/json', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Authorization'=>'token 1', 'Content-Type'=>'application/x-www-form-urlencoded', 'User-Agent'=>'Faraday v0.9.2'}

   You can stub this request with the following snippet:

   stub_request(:post, "https://api.github.com/user/repos").
     with(:body => {"{\"name\":\"a-new-repo\"}"=>nil},
          :headers => {'Accept'=>'application/json', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Authorization'=>'token 1', 'Content-Type'=>'application/x-www-form-urlencoded', 'User-Agent'=>'Faraday v0.9.2'}).
     to_return(:status => 200, :body => "", :headers => {})

   registered request stubs:

   stub_request(:post, "https://api.github.com/user/repos").
     with(:body => {"{\"name\":\"a-new-repo\"}"=>true},
          :headers => {'Authorization'=>'token 1'})
   stub_request(:get, "https://api.github.com/user").
     with(:headers => {'Authorization'=>'token 1'})
   stub_request(:post, "https://github.com/login/oauth/access_token").
     with(:body => {"client_id"=>"20199bec5e5efcee3e7e", "client_secret"=>"48f0b0637b87e952ab035d62cab89dce67fa0669", "code"=>"20"},
          :headers => {'Accept'=>'application/json'})
   stub_request(:get, "https://api.github.com/user/repos").
     with(:headers => {'Authorization'=>'token 1'})
```

**Comment by DanielSeehausen** [comment]
Hi there,

I was unable to reproduce the issue -- the tests were functioning as expected. Please re-examine your incorporation of the create a new repo form. It is expecting to derive a value from the 'new-repo' field. 

Would you mind providing a bit more detail about the issue? Things that are especially useful:

An expanded explanation of what's going on.
Your solution
Steps to reproduce the issue.
Thanks! 💙
