### ISSUE TITLE
Update:: change spec_helper line 29 true -> nil

### ISSUE THREAD

**Issue by pajamaw** [learn-co-curriculum/rails-github-api#7]
last issue comment was correct, just checked against spec of https://github.com/learn-co-curriculum/rails-refactoring-apis-v-000
whose spec's include 
with(body: {"{\"name\":\"a-new-repo\"}"=>nil}
as opposed to, which is in this current lab and appears to cause the error message described in the last issue
with(body: {"{\"name\":\"a-new-repo\"}"=>true}

**Comment by itzsaga** [comment]
I just ran into this. Over a year later. Still not fixed.

**Comment by DanielSeehausen** [comment]
Hi all,

I addressed this in closed issue #11, saying the same: 

I was unable to reproduce the issue -- the tests were functioning as expected. Please re-examine your incorporation of the create a new repo form. It is expecting to derive a value from the 'new-repo' field. 

Unless I am misunderstanding the raised issue here, you may benefit from examining the testing flow we are using here. I would specifically consider the role of stubbing responses and how our tests use them. 

Would you mind providing a bit more detail about the issue? Things that are especially useful:

An expanded explanation of what's going on.
Your solution
Steps to reproduce the issue.
Thanks! 💙
